#ifndef SHELTON_TABLE_H
#define SHELTON_TABLE_H

#include "encode.h"

// Lookup tables for the steno layer
const uint8_t PROGMEM g_left_hand_table[256][ENCODE_SIZE] =
{
    NO_ENTRY,                               // [0]
    ENCODE1(_A),                            // [1]
    ENCODE1(_S),                            // [2]
    ENCODE2(_A, _S),                        // [3]
    ENCODE1(_C),                            // [4]
    ENCODE2(_A, _C),                        // [5]
    ENCODE2(_S, _C),                        // [6]
    ENCODE3(_A, _S, _C),                    // [7]
    ENCODE1(_T),                            // [8]
    ENCODE2(_A, _T),                        // [9]
    ENCODE2(_S, _T),                        // [10]
    ENCODE3(_A, _S, _T),                    // [11]
    ENCODE1(_D),                            // [12]
    ENCODE2(_A, _D),                        // [13]
    ENCODE1(_G),                            // [14]
    ENCODE2(_A, _G),                        // [15]
    ENCODE1(_W),                            // [16]
    ENCODE2(_A, _W),                        // [17]
    ENCODE2(_S, _W),                        // [18]
    NO_ENTRY,                               // [19]
    ENCODE1(_P),                            // [20]
    ENCODE2(_A, _P),                        // [21]
    ENCODE2(_S, _P),                        // [22]
    ENCODE3(_A, _S, _P),                    // [23]
    ENCODE2(_T, _W),                        // [24]
    ENCODE3(_A, _T, _T),                    // [25]
    ENCODE1(_X),                            // [26]
    ENCODE2(_A, _X),                        // [27]
    ENCODE2(_D, _W),                        // [28]
    ENCODE3(_A, _D, _D),                    // [29]
    ENCODE2(_G, _W),                        // [30]
    ENCODE3(_A, _G, _G),                    // [31]
    ENCODE1(_H),                            // [32]
    ENCODE2(_A, _H),                        // [33]
    ENCODE2(_S, _H),                        // [34]
    ENCODE3(_A, _S, _H),                    // [35]
    ENCODE2(_C, _H),                        // [36]
    ENCODE3(_A, _C, _H),                    // [37]
    ENCODE3(_S, _C, _H),                    // [38]
    NO_ENTRY,                               // [39]
    ENCODE2(_T, _H),                        // [40]
    ENCODE3(_A, _T, _H),                    // [41]
    NO_ENTRY,                               // [42]
    ENCODE4(_A, _S, _T, _H),                // [43]
    ENCODE1(_F),                            // [44]
    ENCODE2(_A, _F),                        // [45]
    ENCODE2(_G, _H),                        // [46]
    ENCODE3(_A, _G, _H),                    // [47]
    ENCODE2(_W, _H),                        // [48]
    ENCODE3(_A, _W, _H),                    // [49]
    NO_ENTRY,                               // [50]
    NO_ENTRY,                               // [51]
    ENCODE2(_P, _H),                        // [52]
    ENCODE3(_A, _P, _H),                    // [53]
    ENCODE3(_S, _P, _H),                    // [54]
    ENCODE4(_A, _S, _P, _H),                // [55]
    ENCODE1(_K),                            // [56]
    ENCODE2(_A, _K),                        // [57]
    ENCODE2(_S, _K),                        // [58]
    ENCODE3(_A, _S, _K),                    // [59]
    ENCODE1(_B),                            // [60]
    ENCODE2(_A, _B),                        // [61]
    NO_ENTRY,                               // [62]
    ENCODE3(_A, _B, _B),                    // [63]
    ENCODE1(_N),                            // [64]
    ENCODE2(_A, _N),                        // [65]
    ENCODE2(_S, _N),                        // [66]
    ENCODE3(_A, _N, _N),                    // [67]
    ENCODE1(_Z),                            // [68]
    ENCODE2(_A, _Z),                        // [69]
    ENCODE2(_S, _S),                        // [70]
    ENCODE3(_A, _S, _S),                    // [71]
    ENCODE1(_V),                            // [72]
    ENCODE2(_A, _V),                        // [73]
    ENCODE2(_S, _V),                        // [74]
    NO_ENTRY,                               // [75]
    ENCODE3(_D, _E, _V),                    // [76]
    ENCODE3(_A, _D, _V),                    // [77]
    ENCODE2(_G, _N),                        // [78]
    ENCODE3(_A, _G, _N),                    // [79]
    ENCODE1(_M),                            // [80]
    ENCODE2(_A, _M),                        // [81]
    ENCODE2(_S, _M),                        // [82]
    ENCODE3(_A, _S, _M),                    // [83]
    ENCODE2(_P, _N),                        // [84]
    ENCODE3(_A, _M, _M),                    // [85]
    NO_ENTRY,                               // [86]
    ENCODE3(_A, _P, _P),                    // [87]
    ENCODE1(_J),                            // [88]
    ENCODE2(_A, _J),                        // [89]
    NO_ENTRY,                               // [90]
    NO_ENTRY,                               // [91]
    ENCODE3(_D, _E, _M),                    // [92]
    ENCODE3(_A, _D, _M),                    // [93]
    NO_ENTRY,                               // [94]
    ENCODE3(_A, _D, _J),                    // [95]
    ENCODE1(_Y),                            // [96]
    ENCODE2(_A, _Y),                        // [97]
    ENCODE2(_S, _Y),                        // [98]
    ENCODE3(_A, _S, _Y),                    // [99]
    ENCODE2(_C, _Y),                        // [100]
    ENCODE3(_A, _C, _C),                    // [101]
    NO_ENTRY,                               // [102]
    NO_ENTRY,                               // [103]
    ENCODE2(_T, _Y),                        // [104]
    NO_ENTRY,                               // [105]
    ENCODE3(_S, _T, _Y),                    // [106]
    NO_ENTRY,                               // [107]
    ENCODE2(_D, _Y),                        // [108]
    ENCODE3(_A, _F, _F),                    // [109]
    ENCODE2(_G, _Y),                        // [110]
    ENCODE3(_A, _F, _T),                    // [111]
    ENCODE2(_M, _Y),                        // [112]
    NO_ENTRY,                               // [113]
    NO_ENTRY,                               // [114]
    NO_ENTRY,                               // [115]
    ENCODE2(_P, _Y),                        // [116]
    NO_ENTRY,                               // [117]
    ENCODE3(_S, _P, _Y),                    // [118]
    ENCODE5(_A, _S, _P, _H, _Y),            // [119]
    ENCODE2(_K, _N),                        // [120]
    ENCODE4(_A, _C, _K, _N),                // [121]
    ENCODE2(_X, _Y),                        // [122]
    NO_ENTRY,                               // [123]
    ENCODE2(_B, _Y),                        // [124]
    ENCODE3(_A, _B, _Y),                    // [125]
    NO_ENTRY,                               // [126]
    NO_ENTRY,                               // [127]
    ENCODE1(_R),                            // [128]
    ENCODE2(_A, _R),                        // [129]
    ENCODE3(_S, _E, _R),                    // [130]
    ENCODE3(_A, _R, _R),                    // [131]
    ENCODE2(_C, _R),                        // [132]
    ENCODE3(_A, _C, _R),                    // [133]
    ENCODE3(_S, _C, _R),                    // [134]
    ENCODE4(_A, _S, _C, _R),                // [135]
    ENCODE2(_T, _R),                        // [136]
    ENCODE3(_A, _T, _R),                    // [137]
    ENCODE3(_S, _T, _R),                    // [138]
    NO_ENTRY,                               // [139]
    ENCODE2(_D, _R),                        // [140]
    ENCODE3(_A, _D, _R),                    // [141]
    ENCODE2(_G, _R),                        // [142]
    ENCODE3(_A, _G, _R),                    // [143]
    ENCODE2(_W, _R),                        // [144]
    NO_ENTRY,                               // [145]
    NO_ENTRY,                               // [146]
    NO_ENTRY,                               // [147]
    ENCODE2(_P, _R),                        // [148]
    ENCODE3(_A, _P, _R),                    // [149]
    ENCODE3(_S, _P, _R),                    // [150]
    ENCODE4(_A, _P, _P, _R),                // [151]
    NO_ENTRY,                               // [152]
    ENCODE4(_A, _T, _T, _R),                // [153]
    ENCODE2(_X, _R),                        // [154]
    NO_ENTRY,                               // [155]
    ENCODE3(_D, _E, _R),                    // [156]
    ENCODE4(_A, _D, _D, _R),                // [157]
    NO_ENTRY,                               // [158]
    ENCODE4(_A, _G, _G, _R),                // [159]
    ENCODE2(_R, _H),                        // [160]
    NO_ENTRY,                               // [161]
    ENCODE3(_S, _H, _R),                    // [162]
    NO_ENTRY,                               // [163]
    ENCODE3(_C, _H, _R),                    // [164]
    ENCODE4(_A, _C, _C, _R),                // [165]
    NO_ENTRY,                               // [166]
    NO_ENTRY,                               // [167]
    ENCODE3(_T, _H, _R),                    // [168]
    ENCODE4(_A, _T, _H, _L),                // [169]
    NO_ENTRY,                               // [170]
    NO_ENTRY,                               // [171]
    ENCODE2(_F, _R),                        // [172]
    ENCODE3(_A, _F, _R),                    // [173]
    NO_ENTRY,                               // [174]
    ENCODE4(_A, _F, _F, _R),                // [175]
    NO_ENTRY,                               // [176]
    NO_ENTRY,                               // [177]
    NO_ENTRY,                               // [178]
    NO_ENTRY,                               // [179]
    ENCODE3(_P, _H, _R),                    // [180]
    ENCODE4(_A, _P, _H, _R),                // [181]
    NO_ENTRY,                               // [182]
    NO_ENTRY,                               // [183]
    ENCODE2(_K, _R),                        // [184]
    NO_ENTRY,                               // [185]
    NO_ENTRY,                               // [186]
    NO_ENTRY,                               // [187]
    ENCODE2(_B, _R),                        // [188]
    ENCODE3(_A, _B, _R),                    // [189]
    NO_ENTRY,                               // [190]
    ENCODE4(_A, _B, _B, _R),                // [191]
    ENCODE1(_L),                            // [192]
    ENCODE2(_A, _L),                        // [193]
    ENCODE2(_S, _L),                        // [194]
    ENCODE3(_A, _S, _L),                    // [195]
    ENCODE2(_C, _L),                        // [196]
    NO_ENTRY,                               // [197]
    NO_ENTRY,                               // [198]
    NO_ENTRY,                               // [199]
    ENCODE1(_Q),                            // [200]
    ENCODE2(_A, _Q),                        // [201]
    ENCODE2(_S, _Q),                        // [202]
    ENCODE3(_A, _S, _Q),                    // [203]
    ENCODE3(_D, _E, _L),                    // [204]
    ENCODE3(_A, _C, _Q),                    // [205]
    ENCODE2(_G, _L),                        // [206]
    ENCODE3(_A, _G, _L),                    // [207]
    ENCODE2(_M, _R),                        // [208]
    ENCODE3(_A, _L, _L),                    // [209]
    NO_ENTRY,                               // [210]
    NO_ENTRY,                               // [211]
    ENCODE2(_P, _L),                        // [212]
    ENCODE3(_A, _P, _L),                    // [213]
    ENCODE3(_S, _P, _L),                    // [214]
    ENCODE4(_A, _P, _P, _L),                // [215]
    ENCODE3(_J, _E, _R),                    // [216]
    NO_ENTRY,                               // [217]
    ENCODE4(_S, _E, _R, _V),                // [218]
    NO_ENTRY,                               // [219]
    NO_ENTRY,                               // [220]
    ENCODE4(_A, _D, _D, _L),                // [221]
    NO_ENTRY,                               // [222]
    ENCODE4(_A, _G, _G, _L),                // [223]
    ENCODE2(_L, _Y),                        // [224]
    NO_ENTRY,                               // [225]
    ENCODE3(_S, _L, _Y),                    // [226]
    NO_ENTRY,                               // [227]
    ENCODE3(_C, _R, _Y),                    // [228]
    ENCODE4(_A, _C, _C, _L),                // [229]
    NO_ENTRY,                               // [230]
    NO_ENTRY,                               // [231]
    ENCODE3(_T, _R, _Y),                    // [232]
    NO_ENTRY,                               // [233]
    ENCODE4(_S, _T, _R, _Y),                // [234]
    NO_ENTRY,                               // [235]
    ENCODE2(_F, _L),                        // [236]
    ENCODE3(_A, _F, _L),                    // [237]
    NO_ENTRY,                               // [238]
    ENCODE4(_A, _F, _F, _L),                // [239]
    NO_ENTRY,                               // [240]
    NO_ENTRY,                               // [241]
    NO_ENTRY,                               // [242]
    NO_ENTRY,                               // [243]
    ENCODE3(_P, _H, _L),                    // [244]
    NO_ENTRY,                               // [245]
    NO_ENTRY,                               // [246]
    NO_ENTRY,                               // [247]
    ENCODE2(_K, _L),                        // [248]
    NO_ENTRY,                               // [249]
    NO_ENTRY,                               // [250]
    NO_ENTRY,                               // [251]
    ENCODE2(_B, _L),                        // [252]
    ENCODE3(_A, _B, _L),                    // [253]
    NO_ENTRY,                               // [254]
    NO_ENTRY                                // [255]
};

const uint8_t PROGMEM g_thumbs_table[16][ENCODE_SIZE] =
{
    NO_ENTRY,                               // [0]
    ENCODE1(_A),                            // [1]
    ENCODE1(_O),                            // [2]
    ENCODE2(_I, _O),                        // [3]
    ENCODE1(_E),                            // [4]
    ENCODE2(_E, _A),                        // [5]
    ENCODE2(_I, _E),                        // [6]
    ENCODE2(_E, _E),                        // [7]
    ENCODE1(_U),                            // [8]
    NO_ENTRY,                               // [9]
    ENCODE2(_O, _U),                        // [10]
    ENCODE2(_O, _O),                        // [11]
    ENCODE1(_I),                            // [12]
    NO_ENTRY,                               // [13]
    ENCODE2(_O, _I),                        // [14]
    NO_ENTRY                                // [15]
};

const uint8_t PROGMEM g_right_hand_table[256][ENCODE_SIZE] =
{
    NO_ENTRY,                               // [0]
    ENCODE1(_R),                            // [1]
    ENCODE1(_N),                            // [2]
    ENCODE2(_R, _N),                        // [3]
    ENCODE1(_L),                            // [4]
    ENCODE2(_R, _L),                        // [5]
    ENCODE1(_S),                            // [6]
    ENCODE2(_L, _L),                        // [7]
    ENCODE1(_G),                            // [8]
    ENCODE2(_R, _G),                        // [9]
    ENCODE2(_N, _G),                        // [10]
    ENCODE2(_G, _N),                        // [11]
    ENCODE2(_L, _G),                        // [12]
    NO_ENTRY,                               // [13]
    ENCODE1(_D),                            // [14]
    ENCODE2(_D, _L),                        // [15]
    ENCODE1(_C),                            // [16]
    ENCODE2(_R, _C),                        // [17]
    ENCODE2(_N, _C),                        // [18]
    NO_ENTRY,                               // [19]
    ENCODE1(_P),                            // [20]
    ENCODE2(_R, _P),                        // [21]
    ENCODE2(_S, _P),                        // [22]
    ENCODE2(_P, _L),                        // [23]
    ENCODE1(_B),                            // [24]
    ENCODE2(_R, _B),                        // [25]
    ENCODE2(_G, _G),                        // [26]
    NO_ENTRY,                               // [27]
    ENCODE2(_B, _L),                        // [28]
    NO_ENTRY,                               // [29]
    NO_ENTRY,                               // [30]
    ENCODE2(_L, _B),                        // [31]
    ENCODE1(_H),                            // [32]
    ENCODE1(_W),                            // [33]
    ENCODE1(_V),                            // [34]
    ENCODE2(_W, _N),                        // [35]
    ENCODE1(_Z),                            // [36]
    ENCODE2(_W, _L),                        // [37]
    ENCODE2(_S, _H),                        // [38]
    ENCODE2(_L, _V),                        // [39]
    ENCODE2(_G, _H),                        // [40]
    ENCODE3(_R, _G, _H),                    // [41]
    ENCODE1(_M),                            // [42]
    ENCODE2(_R, _M),                        // [43]
    ENCODE1(_X),                            // [44]
    NO_ENTRY,                               // [45]
    ENCODE2(_S, _M),                        // [46]
    ENCODE2(_L, _M),                        // [47]
    ENCODE2(_C, _H),                        // [48]
    ENCODE3(_R, _C, _H),                    // [49]
    ENCODE3(_N, _C, _H),                    // [50]
    ENCODE2(_R, _V),                        // [51]
    ENCODE2(_P, _H),                        // [52]
    NO_ENTRY,                               // [53]
    NO_ENTRY,                               // [54]
    ENCODE3(_L, _C, _H),                    // [55]
    ENCODE1(_F),                            // [56]
    ENCODE2(_R, _F),                        // [57]
    ENCODE2(_M, _B),                        // [58]
    NO_ENTRY,                               // [59]
    ENCODE2(_L, _F),                        // [60]
    NO_ENTRY,                               // [61]
    ENCODE2(_M, _P),                        // [62]
    NO_ENTRY,                               // [63]
    ENCODE1(_T),                            // [64]
    ENCODE2(_R, _T),                        // [65]
    ENCODE2(_N, _T),                        // [66]
    ENCODE3(_R, _N, _T),                    // [67]
    ENCODE2(_L, _T),                        // [68]
    NO_ENTRY,                               // [69]
    ENCODE2(_S, _T),                        // [70]
    ENCODE3(_R, _S, _T),                    // [71]
    ENCODE1(_K),                            // [72]
    ENCODE2(_R, _K),                        // [73]
    ENCODE2(_N, _K),                        // [74]
    NO_ENTRY,                               // [75]
    ENCODE2(_K, _L),                        // [76]
    NO_ENTRY,                               // [77]
    ENCODE2(_S, _K),                        // [78]
    ENCODE2(_L, _K),                        // [79]
    ENCODE2(_C, _T),                        // [80]
    NO_ENTRY,                               // [81]
    ENCODE4(_T, _I, _O, _N),                // [82]
    NO_ENTRY,                               // [83]
    ENCODE2(_P, _T),                        // [84]
    NO_ENTRY,                               // [85]
    ENCODE3(_N, _S, _T),                    // [86]
    ENCODE2(_L, _P),                        // [87]
    ENCODE2(_C, _K),                        // [88]
    NO_ENTRY,                               // [89]
    ENCODE2(_B, _T),                        // [90]
    NO_ENTRY,                               // [91]
    ENCODE3(_C, _K, _L),                    // [92]
    NO_ENTRY,                               // [93]
    NO_ENTRY,                               // [94]
    NO_ENTRY,                               // [95]
    ENCODE2(_T, _H),                        // [96]
    ENCODE3(_R, _T, _H),                    // [97]
    ENCODE3(_N, _T, _H),                    // [98]
    ENCODE3(_W, _T, _H),                    // [99]
    ENCODE3(_L, _T, _H),                    // [100]
    NO_ENTRY,                               // [101]
    NO_ENTRY,                               // [102]
    NO_ENTRY,                               // [103]
    ENCODE3(_G, _H, _T),                    // [104]
    ENCODE2(_W, _K),                        // [105]
    ENCODE4(_N, _G, _T, _H),                // [106]
    NO_ENTRY,                               // [107]
    ENCODE2(_X, _T),                        // [108]
    NO_ENTRY,                               // [109]
    ENCODE3(_D, _T, _H),                    // [110]
    NO_ENTRY,                               // [111]
    ENCODE3(_T, _C, _H),                    // [112]
    NO_ENTRY,                               // [113]
    NO_ENTRY,                               // [114]
    NO_ENTRY,                               // [115]
    ENCODE3(_P, _T, _H),                    // [116]
    NO_ENTRY,                               // [117]
    NO_ENTRY,                               // [118]
    NO_ENTRY,                               // [119]
    ENCODE2(_F, _T),                        // [120]
    NO_ENTRY,                               // [121]
    NO_ENTRY,                               // [122]
    NO_ENTRY,                               // [123]
    NO_ENTRY,                               // [124]
    NO_ENTRY,                               // [125]
    ENCODE3(_M, _P, _T),                    // [126]
    NO_ENTRY,                               // [127]
    ENCODE1(_S),                            // [128]
    ENCODE2(_R, _S),                        // [129]
    ENCODE2(_N, _S),                        // [130]
    ENCODE3(_R, _N, _S),                    // [131]
    ENCODE2(_L, _S),                        // [132]
    ENCODE3(_R, _L, _S),                    // [133]
    ENCODE2(_S, _S),                        // [134]
    ENCODE3(_L, _L, _S),                    // [135]
    ENCODE2(_G, _S),                        // [136]
    ENCODE3(_R, _G, _S),                    // [137]
    ENCODE3(_N, _G, _S),                    // [138]
    ENCODE3(_G, _N, _S),                    // [139]
    NO_ENTRY,                               // [140]
    NO_ENTRY,                               // [141]
    ENCODE2(_D, _S),                        // [142]
    NO_ENTRY,                               // [143]
    ENCODE2(_C, _S),                        // [144]
    ENCODE3(_R, _C, _S),                    // [145]
    ENCODE4(_N, _C, _E, _S),                // [146]
    NO_ENTRY,                               // [147]
    ENCODE2(_P, _S),                        // [148]
    ENCODE3(_R, _P, _S),                    // [149]
    ENCODE3(_S, _P, _S),                    // [150]
    ENCODE4(_P, _L, _E, _S),                // [151]
    ENCODE2(_B, _S),                        // [152]
    ENCODE3(_R, _B, _S),                    // [153]
    ENCODE3(_G, _G, _S),                    // [154]
    NO_ENTRY,                               // [155]
    ENCODE4(_B, _L, _E, _S),                // [156]
    NO_ENTRY,                               // [157]
    NO_ENTRY,                               // [158]
    ENCODE3(_L, _B, _S),                    // [159]
    ENCODE2(_H, _S),                        // [160]
    ENCODE2(_W, _S),                        // [161]
    ENCODE3(_V, _E, _S),                    // [162]
    ENCODE3(_W, _N, _S),                    // [163]
    ENCODE3(_Z, _E, _S),                    // [164]
    ENCODE3(_W, _L, _S),                    // [165]
    ENCODE4(_S, _H, _E, _S),                // [166]
    ENCODE4(_L, _V, _E, _S),                // [167]
    ENCODE3(_G, _H, _S),                    // [168]
    NO_ENTRY,                               // [169]
    ENCODE2(_M, _S),                        // [170]
    ENCODE3(_R, _M, _S),                    // [171]
    ENCODE3(_X, _E, _S),                    // [172]
    ENCODE3(_R, _L, _D),                    // [173]
    ENCODE3(_S, _M, _S),                    // [174]
    ENCODE3(_L, _M, _S),                    // [175]
    ENCODE1(_D),                            // [176]
    ENCODE2(_R, _D),                        // [177]
    ENCODE2(_N, _D),                        // [178]
    ENCODE2(_W, _D),                        // [179]
    ENCODE3(_P, _H, _S),                    // [180]
    NO_ENTRY,                               // [181]
    NO_ENTRY,                               // [182]
    NO_ENTRY,                               // [183]
    ENCODE2(_D, _G),                        // [184]
    NO_ENTRY,                               // [185]
    ENCODE3(_M, _B, _S),                    // [186]
    NO_ENTRY,                               // [187]
    NO_ENTRY,                               // [188]
    NO_ENTRY,                               // [189]
    ENCODE3(_M, _P, _S),                    // [190]
    NO_ENTRY,                               // [191]
    ENCODE2(_T, _S),                        // [192]
    ENCODE3(_R, _T, _S),                    // [193]
    ENCODE3(_N, _T, _S),                    // [194]
    NO_ENTRY,                               // [195]
    ENCODE3(_L, _T, _S),                    // [196]
    NO_ENTRY,                               // [197]
    ENCODE3(_S, _T, _S),                    // [198]
    ENCODE4(_R, _S, _T, _S),                // [199]
    ENCODE2(_K, _S),                        // [200]
    ENCODE3(_R, _K, _S),                    // [201]
    ENCODE3(_N, _K, _S),                    // [202]
    NO_ENTRY,                               // [203]
    NO_ENTRY,                               // [204]
    NO_ENTRY,                               // [205]
    ENCODE3(_S, _K, _S),                    // [206]
    ENCODE3(_L, _K, _S),                    // [207]
    ENCODE3(_C, _T, _S),                    // [208]
    NO_ENTRY,                               // [209]
    NO_ENTRY,                               // [210]
    NO_ENTRY,                               // [211]
    NO_ENTRY,                               // [212]
    NO_ENTRY,                               // [213]
    NO_ENTRY,                               // [214]
    ENCODE3(_L, _P, _S),                    // [215]
    ENCODE3(_C, _K, _S),                    // [216]
    NO_ENTRY,                               // [217]
    ENCODE3(_B, _T, _S),                    // [218]
    NO_ENTRY,                               // [219]
    ENCODE5(_C, _K, _L, _E, _S),            // [220]
    NO_ENTRY,                               // [221]
    NO_ENTRY,                               // [222]
    NO_ENTRY,                               // [223]
    ENCODE3(_T, _H, _S),                    // [224]
    ENCODE4(_R, _T, _H, _S),                // [225]
    ENCODE4(_N, _T, _H, _S),                // [226]
    ENCODE4(_W, _T, _H, _S),                // [227]
    NO_ENTRY,                               // [228]
    NO_ENTRY,                               // [229]
    NO_ENTRY,                               // [230]
    NO_ENTRY,                               // [231]
    ENCODE4(_G, _H, _T, _S),                // [232]
    ENCODE3(_W, _K, _S),                    // [233]
    ENCODE5(_N, _G, _T, _H, _S),            // [234]
    NO_ENTRY,                               // [235]
    NO_ENTRY,                               // [236]
    NO_ENTRY,                               // [237]
    ENCODE4(_D, _T, _H, _S),                // [238]
    NO_ENTRY,                               // [239]
    ENCODE2(_D, _S),                        // [240]
    ENCODE3(_R, _D, _S),                    // [241]
    ENCODE3(_N, _D, _S),                    // [242]
    ENCODE3(_W, _D, _S),                    // [243]
    ENCODE4(_P, _T, _H, _S),                // [244]
    ENCODE4(_R, _L, _D, _S),                // [245]
    NO_ENTRY,                               // [246]
    ENCODE3(_L, _D, _S),                    // [247]
    NO_ENTRY,                               // [248]
    NO_ENTRY,                               // [249]
    NO_ENTRY,                               // [250]
    NO_ENTRY,                               // [251]
    NO_ENTRY,                               // [252]
    NO_ENTRY,                               // [253]
    ENCODE4(_M, _P, _T, _S),                // [254]
    NO_ENTRY                                // [255]
};

#endif
